# Generated by Django 3.2.9 on 2022-05-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CherryBeauty', '0002_auto_20220508_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CherryBeauty.tag'),
        ),
    ]
