# Generated by Django 3.2.9 on 2022-05-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CherryBeauty', '0003_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog/'),
        ),
    ]
