# Generated by Django 3.2.9 on 2022-05-09 08:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CherryBeauty', '0007_city_oderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
