# Generated by Django 3.2.9 on 2022-05-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CherryBeauty', '0010_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='slugart',
        ),
    ]
