# Generated by Django 4.0.4 on 2022-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CherryBeauty', '0015_customer_bio_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/customer/profile_pic'),
        ),
    ]
